openapi: 3.0.0
info:
  title: Storytel Message Store
  version: 1.0.0
servers:
  - url: http://localhost:8180
paths:
  /message:
    get:
      summary: Get all messages
      responses:
        '200':
          description: A list of messages
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        client_id:
                          type: string
                        content:
                          type: string

  /message/{client_id}:
    post:
      summary: Create a new message
      parameters:
        - name: client_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
              required:
                - content
      responses:
        '200':
          description: Message created
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      client_id:
                        type: string
                      content:
                        type: string
                  message:
                    type: string
                    example: Created message
        '409':
          description: Message already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Message already exists

    put:
      summary: Update an existing message
      parameters:
        - name: client_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
              required:
                - content
      responses:
       '200':
          description: Message updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      client_id:
                        type: string
                      content:
                        type: string
                  message:
                    type: string
                    example: Updated message
       '404':
          description: Message not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: No message exists for client 123
    get:
      summary: Get a message by client_id
      parameters:
        - name: client_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Message found
          content:
            application/json:
              schema:
                type: object
                properties:
                  client_id:
                    type: string
                  content:
                    type: string
        '404':
          description: Message not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: No message exists for client 123
    delete:
      summary: Delete a message
      parameters:
        - name: client_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Message deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Deleted message for client 123
        '404':
          description: Message not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: No message exists for client 123
